apiVersion: logpilot.logpilot.jimyag.com/v1alpha1
kind: LogPilot
metadata:
  labels:
    app.kubernetes.io/name: logpilot
    app.kubernetes.io/managed-by: kustomize
  name: logpilot-sample
spec:
  api: {}
  agent: {}
