apiVersion: logpilot.jimyag.com/v1alpha1
kind: ClusterLogPilotPolicy
metadata:
  name: k8s-events
spec:
  input:
    type: k8sEvent
    batchLen: 500
    config:
      namespaces:
        - default
        - production
  transforms:
    - type: label
      config:
        fields:
          source: k8sEvent
  output:
    type: http
    batchLen: 200
    batchInterval: 60
    config:
      url: "http://log-collector:8080/ingest"
